# Generated by Django 3.1.1 on 2020-09-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=20)),
                ('meal_type', models.CharField(choices=[('BRE', 'Breakfast'), ('LUN', 'Lunch'), ('SUP', 'Supper')], max_length=3)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('AC', 'Air-Conditioned'), ('NAC', 'Non Air-Conditioned'), ('DEL', 'Deluxe'), ('KIN', 'King'), ('QUE', 'Queen')], max_length=3)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('room_charge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
                ('service_charge', models.IntegerField()),
            ],
        ),
    ]
