# Generated by Django 3.1.1 on 2020-09-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_booking_mealselection_serviceselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('HSKP', 'House Keeping'), ('LAUN', 'Laundry')], default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceselection',
            name='service_date',
            field=models.DateField(),
        ),
    ]
