# Generated by Django 3.1.1 on 2020-09-28 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0003_auto_20200920_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='price',
            new_name='meal_charge',
        ),
        migrations.RenameField(
            model_name='mealselection',
            old_name='date',
            new_name='meal_date',
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField()),
                ('serviceselection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.serviceselection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
