# Generated by Django 3.1.1 on 2020-09-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20200928_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='booking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotel.booking'),
        ),
        migrations.AddField(
            model_name='bill',
            name='mealselection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotel.mealselection'),
        ),
    ]
